

interface ConfigListener {
  oneway void notify (in string key, in any value);
};

interface ConfigServer {
  // "where" is the portion of the namespace to listen to
  void add_listener(in string where, in ConfigListener who);  

  // "where" must be a previously-added "where"
  void remove_listener(in string where, in ConfigListener who);
  
  any lookup(in string key);

  void set(in string key, in any value);

  void sync();
};



