

interface ConfigListener {
  oneway void notify (in long cnxn, in string key, in any value);
};

interface ConfigServer {
  // "where" is the portion of the namespace to listen to
  // Returns a connection ID for removal
  long add_listener(in string where, in ConfigListener who);  

  void remove_listener(in long cnxn);
  
  any lookup(in string key);

  void set(in string key, in any value);

  void sync();

  long ping();
};



